# Generated by Django 6.1 on 2026-09-02 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.PositiveIntegerField(db_index=True)),
                ('roll_number', models.CharField(db_index=True, max_length=16, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('father_name', models.CharField(blank=True, max_length=120)),
                ('authorization_no', models.CharField(blank=True, max_length=32)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('test_type', models.CharField(blank=True, max_length=64)),
                ('contact_no', models.CharField(blank=True, max_length=32)),
                ('gender', models.CharField(blank=True, max_length=16)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('exam_city', models.CharField(blank=True, max_length=64)),
                ('graduating_country', models.CharField(blank=True, max_length=64)),
                ('graduating_college', models.CharField(blank=True, max_length=200)),
                ('session', models.CharField(blank=True, max_length=32)),
                ('reporting_time', models.CharField(blank=True, max_length=32)),
                ('test_timing', models.CharField(blank=True, max_length=32)),
                ('exam_center', models.CharField(blank=True, max_length=300)),
                ('center_location', models.URLField(blank=True, max_length=500)),
                ('test_month', models.CharField(blank=True, max_length=32)),
                ('image', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='VerificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_id', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_attempts', to='candidates.candidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
